spring:
  datasource:
    url: jdbc:postgresql://postgres:nbMmvSyyluqLIKOiuCnuuqtHQOSSzOML@viaduct.proxy.rlwy.net:13120/railway

    username: ${PGUSER}
    password: ${PGPASSWORD}
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: create
